### PR TITLE
Introduce New Font To Open Hexagon: Open Square

### PR DESCRIPTION
**Pull request by Morxemplum**
Open Hexagon Font Test

## The New Font
I've been working on this font for at least the past 6 months now, and I'm glad to say that it is finished enough for it to be in Open Hexagon. This font is called Open Square, and it's a font that has some inspiration from the Forced Square font. And before you worry about any legal issues, I've contacted the owner behind the font and he said it was fine.

This font is similar to Imagine and Forced Square in that it is a square font with minimalistic geometry, but it obviously has key differences in many of the glyphs to distinguish itself. The best part about the font is since I created it, we have FULL RIGHTS to the font. We can easily expand the font to work with new languages and have new glyphs if we want to. Currently, it supports about the same number of characters as Forced Square, and that is only the beginning. 

The font is meant to evolve with the game. As the game gets updated, so will the font. The font, similar to the game, is open-sourced, so within the `art` folder is a new `font` folder that has the project files that people can edit to improve the font. It also has a TTC file for people to easily install the font onto their system, and it has standalone TTF files to be used as assets by the game.

I'm still a little fuzzy on the legal mumbo jumbo so I can't think of any licensing for it yet, but hopefully, I can get a license written down.

## About This PR in particular
The font will be rolled out in multiple PRs. This PR is focused mainly on introducing the font to the GitHub repository and replacing the assets of the game with the new font. This PR doesn't touch any game code, as that will be done in the next PR to get the game to actually render the new font. Considering the font has slight differences in size and width compared to Forced Square, I want to do all the trial and erroring in another PR. You will notice that all relevant PSD files have been modified to now use the new font instead of Forced Square, along with some of the PNGs.

However, I couldn't modify some of the PNGs because they don't have a corresponding PSD file for them. I wonder why some of the PNGs don't have PSDs and I would like for them to be uploaded if they could. 

## Modifications to the Font
If any font artists are interested in expanding the font, they will need to use the FontForge program in order to open and modify the .sfd files. From there they can do anything they want with the font, including adding glyphs, changing some characteristics, etc.

If any font artists want to make a PR in regards to modifying the font, there should be a "font" label that can be used to indicate that the PR is focusing on making a font change.

### CODE REVIEW

**Comment by SuperV1234** [comment]
Looks great. I have to admit I was skeptical, but I like the final result. 

---

> I'm still a little fuzzy on the legal mumbo jumbo so I can't think of any licensing for it yet, but hopefully, I can get a license written down.

If this font is going to officially be used for Open Hexagon, it should use the [same license](https://github.com/SuperV1234/SSVOpenHexagon/blob/master/LICENSE) or one compatible with it. I also think it would be nice to use a permissive open-source license, as the Open Hexagon project is also meant to be something people can freely hack on and reuse, as long as they credit the original source.

---

> However, I couldn't modify some of the PNGs because they don't have a corresponding PSD file for them. I wonder why some of the PNGs don't have PSDs and I would like for them to be uploaded if they could.

Some PSDs might have been lost with time. Which ones are missing? I can check if they are still on my hard drive somewhere.

---

PR looks good so far, but it should probably target a new branch. Maybe something like a `new_font` branch, which will then be merged into `2.0.7` or whatever the new version will be. It will be easier to keep track of all font-related changes that way.

**Comment by Morxemplum** [comment]
> PR looks good so far, but it should probably target a new branch. Maybe something like a new_font branch, which will then be merged into 2.0.7 or whatever the new version will be. It will be easier to keep track of all font-related changes that way.

So I'm guessing you want me to try and keep all the font stuff on one PR? That's completely understandable. I would've liked to do all the game code changing in a separate PR but I can understand where you're coming from.

As for the PSD files, there is `githubohlogo.png`, `headercapsule.png`, the icons, `librarycapsule.png`, `librarylogo.png`, `smallcapsule.png`, all of the store banner stuff, `workshop_header.png`, and `workshop_example_level.png`

**Comment by SuperV1234** [comment]
> So I'm guessing you want me to try and keep all the font stuff on one PR? That's completely understandable. I would've liked to do all the game code changing in a separate PR but I can understand where you're coming from.

No, I want multiple PRs, but not targeting `master`. They should target a new branch, so that all the font-related changes are grouped together. Then we can merge that branch into `master`.

**Comment by Morxemplum** [comment]
I see. So how will we go about this PR then?

**Comment by Morxemplum** [comment]
I will close the PR and open up another branch.

**Comment by Morxemplum** [comment]
Reopening this, but to go to a different branch

**Comment by SuperV1234** [comment]
LGTM

**Comment by SuperV1234** [comment]
> As for the PSD files, there is `githubohlogo.png`, `headercapsule.png`, the icons, `librarycapsule.png`, `librarylogo.png`, `smallcapsule.png`, all of the store banner stuff, `.png`, and `workshop_example_level.png`

The only one I could find is the workshop example one, all the other would have to be remade from scratch.

https://vittorioromeo.info/Misc/Linked/Workshop_header.psd

**Pull request merged**
