### PR TITLE
Camera shake in Lua and l_getLevelTime

### PR DESCRIPTION
**Pull request by MultHub**
l_getLevelTime(): returns current time
s_setCameraShake(int mValue): set camera shake
s_getCameraShake(): returns camera shake

obviously isn't perfect, feel free to change anything

### CODE REVIEW

**Comment by MultHub** [comment]
just found a bug - messages displayed by Lua are broken

**Comment by MultHub** [comment]
actually a bug with open hexagon...

**Comment by SuperV1234** [comment]
I'll look into the pull request as soon as possible. Can you also describe the bug you discovered and how to reproduce it?

**Comment by MultHub** [comment]
Text moved to top left corner of the screen
How to reproduce: Disable text outlines, then restart the game

**Comment by MultHub** [comment]
Random bug in Slither:
no walls at 0.5 difficulty

**Pull request merged**
