### PR TITLE
Add How to build on Linux to README

### PR DESCRIPTION
**Pull request by treier57lol**

### CODE REVIEW

**Comment by SuperV1234** [comment]
Hey @treier57lol, thanks for the PR. What distro did you test it on? It would be nice to mention that in the README.

**Comment by treier57lol** [comment]
I tested building on Manjaro which is based on Arch Linux.

**Comment by treier57lol** [comment]
Also, I found out that you can clone the repository while also including the submodules and updating them by using `git clone --recurse-submodules --remote-submodules`, eliminating the need for the `init-repository.sh` script.

**Comment by SuperV1234** [comment]
Excellent! Thank you so much.

**Pull request merged**
